title: Home
views:
  - title: Home
    badges:
      - device_tracker.alex
      - device_tracker.spencer
      - sensor.dark_sky_temperature
      - sensor.dark_sky_minutely_summary
    cards:
      - type: entities
        title: Master Bedroom
        show_header_toggle: true
        entities:
          - switch.sonoff1
          - entity: switch.master_bathroom_outlet
            name: Bathroom Outlet
      - type: entities
        title: Downstairs
        show_header_toggle: true
        entities:
          - switch.front_porch
          - entity: switch.downstairs_lamp
            name: Lamp
          - switch.foyer
          - switch.breakfast_nook
          - switch.bar_pendants
          - light.dining_room
          - switch.porch_lights
          - light.kitchen_accent
      - type: entities
        title: Bonus Room
        show_header_toggle: true
        entities:
          - switch.sonoff2

  - title: Automations
    cards:
      - type: entities
        title: Lights and Switches
        entities:
          - automation.don_t_burn_the_house_down
          - automation.master_lights_off_when_away
          - automation.master_lights_on_at_night_if_someone_is_home
          - automation.master_lights_on_when_someone_gets_home
          - automation.kitchen_accent_lights_on_at_8am
          - automation.kitchen_accent_lights_off_at_midnight

      - type: entities
        title: Themes
        entities:
          - automation.dark_theme_at_night
          - automation.light_theme_during_the_day

      - type: entities
        title: Outside Lights
        entities:
          - automation.porch_light_on_around_sunset
          - automation.screened_porch_lights_off_at_night
          - automation.screened_porch_lights_on_at_sunset
          - automation.turn_the_porch_light_off_at_night

      - type: entities
        title: Cameras
        entities:
          - automation.motion_detected_in_nursery
          - automation.reset_nursery_motion_detection_debounce
          #- automation.turn_night_mode_on_cameras_off_at_sunrise
          #- automation.turn_night_mode_on_cameras_to_auto_at_sunet

      - type: entities
        title: Christmas
        entities:
          - automation.christmas_lights_off_at_midnight
          - automation.christmas_lights_on_at_8am
  - title: Cameras
    icon: mdi:camera
    cards:
      - type: picture-entity
        entity: camera.nursery
      - type: picture-entity
        entity: camera.living_room

      # - type: entity-filter
      #   title: Device Trackers
      #   show_header_toggle: true
      #   entities:
      #     - device_tracker.alex
      #     - device_tracker.alex_unifi
      #     - device_tracker.spencer
      #     - device_tracker.spencer_unifi
      #   state_filter:
      #     - 'home'
      #   card:
      #     type: glance
      #     title: My Device Trackers

      # - type: entities
      #   title: Input Booleans
      #   show_header_toggle: true
      #   entities:
      #     - input_boolean.enable_motion_detect_nursery
      #     - input_boolean.motion_detect_nursery_debounce
      #     - input_boolean.test_switch

      # - type: entities
      #   title: Light
      #   show_header_toggle: true
      #   entities:
      #     - light.kitchen_accent

      # - type: entities
      #   title: Remote
      #   show_header_toggle: true
      #   entities:
      #     - remote.bonus_room

      # - type: entities
      #   title: Zwaves
      #   show_header_toggle: true
      #   entities:
      #     - zwave.aeotec_dsa02203_zstick_s2
      #     - zwave.ge_14292_inwall_smart_toggle_switch
