title: Home

resources:
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/roku-card/roku-card.js
    type: module

background: center / cover no-repeat url("/local/lovelace/background.png") fixed
views:
  - title: Home
    icon: mdi:home
    badges:
      - person.alex
      - person.spencer
      - sensor.dark_sky_temperature
      - sensor.dark_sky_minutely_summary
    cards:
      - type: "custom:compact-custom-header"
        main_config: true
        background: 'rgba(150, 150, 150, 0.2)'
        menu: show
        options: show
        voice: show
        notifications: clock
        clock_format: '24'
        clock_date: true
        date_locale: en-gb
        disable: false

      - type: entities
        title: Master Bedroom
        show_header_toggle: true
        background: 'rgba(150, 150, 150, 0.2)'
        entities:
          - switch.sonoff1
          - entity: switch.master_bathroom_outlet
            name: Bathroom Outlet
      - type: entities
        title: Downstairs
        show_header_toggle: true
        entities:
          - switch.front_porch
          - entity: switch.downstairs_lamp
            name: Lamp
          - switch.breakfast_nook
          - switch.bar_pendants
          - light.dining_room
          - switch.porch_lights
          - light.kitchen_accent
      - type: entities
        title: Bonus Room
        show_header_toggle: true
        entities:
          - switch.sonoff2
      - type: entities
        title: Misc
        entities:
          - switch.nursery_camera

  - title: Bonus Room
    icon: mdi:television
    cards:
      - type: "custom:compact-custom-header"
      - type: custom:roku-card
        entity: media_player.living_room
        name: Roku
        theme: darkpurple
        # tv: true
        # power:
        #   service: switch.turn_on
        #   service_data:
        #     entity_id: switch.bedroom_tv_power

  - title: Automations
    icon: mdi:clock-outline
    cards:
      - type: "custom:compact-custom-header"

      - type: entities
        title: Lights and Switches
        entities:
          - automation.don_t_burn_the_house_down
          - automation.master_lights_off_when_away
          - automation.master_lights_on_at_night_if_someone_is_home
          - automation.master_lights_on_when_someone_gets_home
          - automation.kitchen_accent_lights_on_at_8am
          - automation.kitchen_accent_lights_off_at_midnight

      - type: entities
        title: Themes
        entities:
          - automation.dark_theme_at_night
          - automation.light_theme_during_the_day

      - type: entities
        title: Outside Lights
        entities:
          - automation.porch_light_on_around_sunset
          - automation.screened_porch_lights_off_at_night
          - automation.screened_porch_lights_on_at_sunset
          - automation.turn_the_porch_light_off_at_night

      - type: entities
        title: Cameras
        entities:
          - automation.motion_detected_in_nursery
          - automation.reset_nursery_motion_detection_debounce
          #- automation.turn_night_mode_on_cameras_off_at_sunrise
          #- automation.turn_night_mode_on_cameras_to_auto_at_sunet

      - type: entities
        title: Christmas
        entities:
          - automation.christmas_lights_off_at_midnight
          - automation.christmas_lights_on_at_8am
#  - title: Cameras
#    icon: mdi:camera
#    cards:
#      - type: "custom:compact-custom-header"
#
#      - type: picture-entity
#        entity: camera.nursery
#
#      - type: picture-entity
#        entity: camera.living_room

