- platform: generic
  name: Living Room
  still_image_url: !secret living_room_still_image_url
  stream_url: !secret living_room_stream_url
  username: !secret camera_username
  password: !secret camera_password
