- platform: generic
  name: Nursery
  still_image_url: !secret nursery_still_image_url
  stream_url: !secret nursery_stream_url
  username: !secret camera_username
  password: !secret camera_password
