# Turn off the master bedroom lights when noone is home
alias: "Master lights off when away"
initial_state: True
trigger:
  platform: state
  entity_id: group.all_devices
  from: 'home'
  to: 'not_home'
action:
  - service: switch.turn_off
    entity_id: switch.sonoff1
