# Notify if motion in nursery
alias: 'Motion detected in nursery'
#trigger:
#  platform: webhook
#  webhook_id: nursery_motion_detected
trigger:
  payload: 'ON'
  platform: mqtt
  topic: myhome/camera1/motion
condition:
  - condition: state
    entity_id: input_boolean.nursery_motion_detect_enabled
    state: "on"
  - condition: state
    entity_id: input_boolean.nusery_motion_detect_debounce
    state: "off"
action:
  #- service: script.turn_on
  #  entity_id: script.nursery_screenshot_notification
  - service: notify.telegram_alex
    data:
      message: "Motion detected in the nursery"
  - service: notify.telegram_spencer
    data:
      message: "Motion detected in the nursery"
  - service: input_boolean.turn_on
    entity_id: input_boolean.nusery_motion_detect_debounce
