# Notify if motion in nursery
alias: 'Murder mystery party'
trigger:
  platform: state
  entity_id: input_boolean.test_switch
  from: 'off'
  to: 'on'
action:
  - service: script.turn_on
    entity_id: script.murder_mystery_murder
