alias: "Reset nursery motion detection debounce"
trigger:
  platform: state
  entity_id: input_boolean.nusery_motion_detect_debounce
  from: "off"
  to: "on"
action:
  - delay: "00:05:00"
  - service: input_boolean.turn_off
    entity_id: input_boolean.nusery_motion_detect_debounce
