default_view:
  name: Home
  view: true
  entities:
    - sensor.dark_sky_temperature
    - sensor.dark_sky_minutely_summary
    - device_tracker.alex
    - device_tracker.spencer
    - group.master_bedroom
    - group.bonus_room
    - group.living_room
    - group.outside
