alias: Turn night mode on cameras off at Sunrise
trigger:
  - event: sunrise
    platform: sun
    offset: "02:00:00"
action:
  - service: mqtt.publish
    data:
      topic: "myhome/wyze2/night_mode/auto/set"
      payload: "OFF"
  - service: mqtt.publish
    data:
      topic: "myhome/wyze2/night_mode/set"
      payload: "OFF"
  - service: mqtt.publish
    data:
      topic: "myhome/wyze2/ir/set"
      payload: "OFF"
