alias: 'Porch light on around sunset'
trigger:
  - platform: sun
    event: sunset
action:
  - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
  - service: switch.turn_on
    entity_id: switch.front_porch
