# Turn on the master bedroom lights at night IF someone is home
alias: "Master lights on at night if someone is home"
initial_state: False
trigger:
  - platform: sun
    event: sunset
condition:
  - condition: state
    entity_id: group.all_devices
    state: 'home'
action:
  service: switch.turn_on
  entity_id: switch.sonoff1
