homeassistant:
  customize:
    group.all_automations:
      hidden: false

input_boolean:
  test_switch:
    initial: off
  enable_motion_detect_nursery:
    initial: off
    name: "Enable nursery motion detection"
    icon: mdi:run-fast
  motion_detect_nursery_debounce:
    initial: off
    name: "Nursery motion detection debounce"

automation:
  # Turn off the bathroom outlet when Spencer leaves
  - id: dont_burn_the_house_down
    alias: "Don't burn the house down"
    initial_state: True
    trigger:
      platform: state
      entity_id: device_tracker.spencer_unifi
      from: 'home'
      to: 'not_home'
    action:
      service: switch.turn_off
      entity_id: switch.tplink_1

  # Turn on the master bedroom lights at night IF someone is home
  - id: master_lights_on_at_night
    alias: "Master lights on at night if someone is home"
    initial_state: False
    trigger:
      - platform: sun
        event: sunset
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
    action:
      service: switch.turn_on
      entity_id: switch.sonoff1

  # Turn on the master bedroom lights when someone gets home
  # if it is nighttime
  - id: master_lights_on_at_home
    alias: "Master lights on when someone gets home"
    initial_state: False
    trigger:
      platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      service: switch.turn_on
      entity_id: switch.sonoff1

  # Turn off the master bedroom lights when noone is home
  - id: master_lights_on_night
    alias: "Master lights off when away"
    initial_state: True
    trigger:
      platform: state
      entity_id: group.all_devices
      from: 'home'
      to: 'not_home'
    action:
      service: switch.turn_off
      entity_id: switch.sonoff1

  - id: evening_porch_on
    alias: 'Porch light on around sunset'
    trigger:
      - platform: sun
        event: sunset
    action:
      - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_on
        entity_id: switch.front_porch

  - id: night_porch_off
    alias: 'Turn the porch light off at night'
    trigger:
      - platform: time
        at: '23:00:00'
    action:
      - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_off
        entity_id: switch.front_porch

  - id: night_dark_theme
    alias: 'Dark theme at night'
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: frontend.set_theme
        data:
          name: midnight

  - id: day_light_theme
    alias: 'Light theme during the day'
    trigger:
      - platform: sun
        event: sunrise
    action:
      - service: frontend.set_theme
        data:
          name: default

  - id: alex_home_notification
    alias: 'Alex home notification'
    trigger:
      platform: state
      entity_id: device_tracker.alex_unifi
      from: 'not_home'
      to: 'home'
    action:
      service: notify.pushbullet
      data:
        title: 'Alex is home'
        message: 'Alex is home'

  - id: screened_porch_on_at_sunet
    alias: 'Screened porch lights on at sunset'
    trigger:
      - platform: sun
        event: sunset
    action:
      service: switch.turn_on
      entity_id: switch.05200743bcddc2e99def

  - id: screened_porch_of_at_11
    alias: 'Screened porch lights off at 11'
    trigger:
      - platform: time
        at: '23:00:00'
    action:
      service: switch.turn_off
      entity_id: switch.05200743bcddc2e99def

  - id: christmas_lights_off_at_midnight
    alias: 'Christmas lights off at midnight'
    trigger:
      - platform: time
        at: '00:00:00'
    action:
      - service: switch.turn_off
        entity_id: switch.05200743bcddc2e9a04d
      - service: light.turn_off
        entity_id: light.kitchen_accent

  - id: christmas_lights_on_8am
    alias: "Christmas lights on at 8am"
    trigger:
      - platform: time
        at: '08:00:00'
    action:
      - service: switch.turn_on
        entity_id: switch.05200743bcddc2e9a04d
      - service: light.turn_on
        entity_id: light.kitchen_accent

  # Notify if motion in nursery
  - id: motion_detected_nursery
    alias: 'Motion detected in nursery'
    trigger:
      payload: 'ON'
      platform: mqtt
      topic: myhome/camera1/motion
    condition:
      - condition: state
        entity_id: input_boolean.enable_motion_detect_nursery
        state: "on"
      - condition: state
        entity_id: input_boolean.motion_detect_nursery_debounce
        state: "off"
    action:
      - service: notify.telegram_alex
        data_template:
          message: "Motion detected in nursery"
      - service: notify.telegram_spencer
        data_template:
          message: "Motion detected in nursery"
      - service: notify.motion_detect_nursery
        data_template:
          message: "Motion detected in nursery"
      - service: input_boolean.turn_on
        entity_id: input_boolean.motion_detect_nursery_debounce

  - id: reset_motion_detected_nursery_debounce
    alias: "Reset nursery motion detection debounce"
    trigger:
      platform: state
      entity_id: input_boolean.motion_detect_nursery_debounce
      from: "off"
      to: "on"
    action:
      - delay: "00:05:00"
      - service: input_boolean.turn_off
        entity_id: input_boolean.motion_detect_nursery_debounce

  # - id: bonus_room_activity_plex_on
  #   alias: "Watch Plex in Bonus Room"
  #   initial_state: False
  #   trigger:
  #     platform: state
  #     entity_id: input_boolean.bonus_room_plex
  #     from: 'off'
  #     to: 'on'
  #   action:
  #     - service: remote.turn_on
  #       entity_id: remote.bonus_room
  #       data:
  #         activity: "Watch Plex"

  # - id: bonus_room_activity_plex_off
  #   alias: "Bonus Room Media Off"
  #   initial_state: False
  #   trigger:
  #     platform: state
  #     entity_id: input_boolean.bonus_room_plex
  #     from: 'on'
  #     to: 'off'
  #   action:
  #     - service: remote.turn_on
  #       entity_id: remote.bonus_room
  #       data:
  #         activity: "PowerOff"
