homeassistant:
  customize:
    group.all_automations:
      hidden: false

automation:
  # Turn off the bathroom outlet when Spencer leaves
  - id: dont_burn_the_house_down
    alias: "Don't burn the house down"
    initial_state: True
    trigger:
      platform: state
      entity_id: device_tracker.spencer_unifi
      from: 'home'
      to: 'not_home'
    action:
      service: switch.turn_off
      entity_id: switch.tplink_1

  # Turn on the master bedroom lights at night IF someone is home
  - id: master_lights_on_at_night
    alias: "Master lights on at night if someone is home"
    initial_state: True
    trigger:
      - platform: sun
        event: sunset
    condition:
      - condition: state
        entity_id: group.all_devices
        state: 'home'
    action:
      service: switch.turn_on
      entity_id: switch.sonoff1

  # Turn on the master bedroom lights when someone gets home
  # if it is nighttime
  - id: master_lights_on_at_home
    alias: "Master lights on when someone gets home"
    initial_state: True
    trigger:
      platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      service: switch.turn_on
      entity_id: switch.sonoff1

  # Turn off the master bedroom lights when noone is home
  - id: master_lights_on_night
    alias: "Master lights off when away"
    initial_state: True
    trigger:
      platform: state
      entity_id: group.all_devices
      from: 'home'
      to: 'not_home'
    action:
      service: switch.turn_off
      entity_id: switch.sonoff1

  # - id: evening_porch_on
  #   alias: 'Porch light on around sunset'
  #   trigger:
  #     - platform: sun
  #       event: sunset
  #   action:
  #     - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
  #     - service: switch.turn_on
  #       entity_id: switch.porch_light_switch

  # - id: night_porch_off
  #   alias: 'Turn the porch light off at night'
  #   trigger:
  #     - platform: time
  #       at: '23:00:00'
  #   action:
  #     - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
  #     - service: switch.turn_off
  #       entity_id: switch.porch_light_switch

  - id: night_dark_theme
    alias: 'Change to a dark theme at night'
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: frontend.set_theme
        data:
          name: midnight

  - id: day_light_theme
    alias: 'Change to a light theme during the day'
    trigger:
      - platform: sun
        event: sunrise
    action:
      - service: frontend.set_theme
        data:
          name: default

  - id: alex_home_notification
    alias: 'Alex home notification'
    trigger:
      platform: state
      entity_id: device_tracker.alex_unifi
      from: 'not_home'
      to: 'home'
    action:
      service: notify.pushbullet
      data:
        title: 'Alex is home'
        message: 'Alex is home'
