# automation:
#   - id: evening_porch_on
#     alias: 'Porch light on around sunset'
#     trigger:
#       - platform: sun
#         event: sunset
#     action:
#       - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
#       - service: switch.turn_on
#         entity_id: switch.porch_light_switch

#   - id: night_porch_off
#     alias: 'Turn the porch light off at night'
#     trigger:
#       - platform: time
#         at: '23:00:00'
#     action:
#       - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
#       - service: switch.turn_off
#         entity_id: switch.porch_light_switch

#   - id: night_dark_theme
#     alias: 'Change to a dark theme at night'
#     trigger:
#       - platform: sun
#         event: sunset
#     action:
#       - service: frontend.set_theme
#         data:
#           name: midnight

#   - id: day_light_theme
#     alias: 'Change to a light theme during the day'
#     trigger:
#       - platform: sun
#         event: sunrise
#     action:
#       - service: frontend.set_theme
#         data:
#           name: default
