homeassistant:
  customize:
    switch.sonoff1:
      friendly_name: "Lamp"
    switch.sonoff2:
      friendly_name: "Lamp"

switch:
  - platform: mqtt
    name: "sonoff1"
    command_topic: "cmnd/sonoff1/power"
    state_topic: "stat/sonoff1/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "sonoff2"
    command_topic: "cmnd/sonoff2/power"
    state_topic: "stat/sonoff2/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
