homeassistant:
  customize:
    sensor.dark_sky_temperature:
      friendly_name: Temp
    sensor.dark_sky_minutely_summary:
      friendy_name: Right Now

sensor:
  - platform: darksky
    api_key: !secret darksky_key
    scan_interval: 60
    monitored_conditions:
      - summary
      - temperature
      - minutely_summary
      - hourly_summary
