homeassistant:
  customize:
    ################################################
    ## DIMMERS
    ################################################
    light.breakfast_nook_level:
      friendly_name: Breakfast Nook

    ################################################
    ## SWITCHES
    ################################################
    switch.front_porch:
      friendly_name: Front Porch

    switch.kitchen_table:
      friendly_name: Kitchen Table

zwave:
  usb_path: /dev/ttyUSB0
  device_config: !include ../zwave_device_config.yaml
