homeassistant:
  customize:
    ################################################
    ## DIMMERS
    ################################################
    light.breakfast_nook_level:
      friendly_name: Breakfast Nook

    ################################################
    ## SWITCHES
    ################################################
    switch.front_porch:
      friendly_name: Front Porch

zwave:
  usb_path: /dev/ttyUSB1
  device_config: !include ../zwave_device_config.yaml
